github: [billlzzz10]                     # GitHub Sponsors username ของคุณ
ko_fi: [billlzzz10]                  # Ko-fi username (ถ้ามี)
custom: ['https://bl1nk.dev/support']   # ลิงก์อื่น ๆ เช่นหน้า support ของคุณ
