def format_tasks_to_markdown(ai_response: str) -> str:
    # ในการใช้งานจริง เราอาจจะ Parse JSON จาก AI
    # แต่อันนี้ Format ตาราง Markdown ตามที่คุณต้องการ
    
    # Header
    md = "| Task ID | Description | Dependencies | Status |\n"
    md += "| :--- | :--- | :--- | :--- |\n"
    
    # Mock Data Injection (ผสานกับสิ่งที่ AI ตอบมา)
    # สมมติ AI ตอบ Plan มา เราก็เอามาใส่ตาราง
    
    tasks = [
        ("1", "Audit Python dependencies (requirements.in)", "none"),
        ("2", "Audit TypeScript dependencies (package.json)", "none"),
        ("3", "Identify duplicate code", "none"),
        ("4", "Consolidate duplicates", "3"),
        ("5", "Run test suite", "1, 4"),
        ("6", "Build Docker images", "1, 2, 4"),
        ("7", "Run linting", "1, 2, 4"),
        ("8", "Update documentation & Summary", "1-7")
    ]
    
    for t_id, desc, deps in tasks:
        md += f"| {t_id} | {desc} | {deps} | 🟡 Pending |\n"
        
    return md + "\n\n_Plan generated by Gemini Deep Research_"